name: 'python-youtube-action'
description: 'here is description'

inputs:
  YOUTUBE_API_KEY:
    description: 'here is description'
    required:    true

runs:
  using: 'composite'
  steps:
    - shell: bash
      id: setup
      run: |
        sudo apt update
        sudo apt install -y python3
        sudo apt upgrade
        sudo python3 -m pip install --upgrade requests
        
    - shell: bash
      id: automation
      run: |
        cd ${{ github.action_path }}
        sudo python3 -m pip install -r requirements.txt
        python3 rank.py ${{ inputs.YOUTUBE_API_KEY }}

