# This is a basic workflow to help you get started with Actions

name: build_site

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 22 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches:
    - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    env:
      YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY}}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: 'echo current datetime'
        env:
          TZ: 'Asia/Tokyo'
        run: |
          echo "CURRENT_DATETIME=$(date +'%Y/%m/%d(%a) %H:%M:%S')"
      
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9.12' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - name: 'pip setting'
        run: |
          python -m pip install --upgrade pip
          pip install pandas            
          pip install google-api-python-client
      - name: 'run python'
        working-directory: 'scripts'
        run: |
          python rank.py ${{ env.YOUTUBE_API_KEY }} 9
          mv youtube_rank.md ./../README.md
      - name: 'commit files'
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add README.md
          git commit -m 'update README.md'
          git push origin main
