# This is a basic workflow to help you get started with Actions

name: build_site

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 22 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches:
    - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    env:
      YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY}}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: 'echo current datetime'
        env:
          TZ: 'Asia/Tokyo'
        run: echo "CURRENT_DATETIME:$(date +'%Y/%m/%d(%a) %H:%M:%S')"

      #- uses: yarakigit/youtube_ranking_build@main
      #  if: ${{ env.YOUTUBE_API_KEY }} != null
      #  with:
      #    YOUTUBE_API_KEY: ${{ env.YOUTUBE_API_KEY }}
      - shell: bash
        id: setup
        run: |
          sudo apt update
          sudo apt install -y python3
          sudo apt upgrade
          sudo python3 -m pip install --upgrade requests
     
      - shell: bash
        id: automation
        run: |
          python --version
          cd ${{ github.action_path }}
          sudo python3 -m pip install -r requirements.txt
          python3 rank.py ${{ env.YOUTUBE_API_KEY }}
